controller_list:
  - name: fake_right_arm_controller
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
  - name: fake_right_hand_controller
    joints:
      - gripper_r_joint_r